Repository optakt/flow-dps, pull requests merged in 2021-06, with the labels that each got.

#132 Add GRPC API documentation
  docs/architecture.md
  docs/dps-api.md
Labels: documentation

#67 Update introduction documentation
  docs/introduction.md
Labels: documentation

#115 Add option for binary output to snapshot tool
  cmd/create-index-snapshot/README.md
  cmd/create-index-snapshot/main.go
Labels: tools

#182 Add height-by-block index
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/server.go
  api/dps/server_test.go
  cmd/extract-ledger-payloads/index.go
  docs/architecture.md
  models/index/reader.go
  models/index/writer.go
  service/chain/disk.go
  service/index/reader.go
  service/index/writer.go
  service/mapper/mapper.go
  service/storage/operations.go
  service/storage/prefixes.go
  testing/mocks/reader.go
  testing/mocks/writer.go
Labels: documentation, feature

#186 Add convert package unit tests
  models/convert/paths_test.go
  models/convert/types_test.go
  models/convert/values_test.go
Labels: testing

#184 Add storage package unit tests
  service/chain/disk_test.go
  service/index/writer.go
  service/storage/auxiliary.go
  service/storage/auxiliary_test.go
  service/storage/encoding_test.go
  service/storage/operations.go
  service/storage/operations_test.go
  testing/helpers/badger.go
Labels: testing

#197 Add logging to DPS server
  cmd/flow-dps-server/main.go
  go.mod
  go.sum
Labels: improvement

#163 Rosetta block integration tests
  api/rosetta/data_balance_integration_test.go
  api/rosetta/data_block_integration_test.go
Labels: testing

#198 Use BypassLockGuard in Indexer and ReadOnly in Server
  cmd/create-index-snapshot/main.go
  cmd/extract-block-events/main.go
  cmd/extract-block-headers/main.go
  cmd/extract-ledger-payloads/main.go
  cmd/flow-dps-server/main.go
  docs/introduction.md
Labels: documentation, improvement

#202 Rosetta balance integration tests - error validation and code updates
  api/rosetta/data_balance_integration_test.go
  api/rosetta/data_block_integration_test.go
Labels: testing

#210 Add go generate target to compute version file for Rosetta API
  gen/version.go
  go.mod
  go.sum
  rosetta/configuration/version.go
Labels: improvement

#209 Add transaction index
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/index_test.go
  api/dps/server.go
  api/dps/server_test.go
  cmd/extract-ledger-payloads/index.go
  docs/architecture.md
  models/index/reader.go
  models/index/writer.go
  service/chain/disk.go
  service/chain/disk_test.go
  service/index/reader.go
  service/index/writer.go
  service/mapper/chain.go
  service/mapper/mapper.go
  service/storage/operations.go
  service/storage/operations_test.go
  service/storage/prefixes.go
  testing/mocks/reader.go
  testing/mocks/writer.go
Labels: documentation, feature

#225 Small miscellaneous fixes (typos & naming)
  .github/workflows/ci.yml
  api/rosetta/data_block_integration_test.go
  cmd/extract-block-events/README.md
  cmd/extract-block-headers/README.md
  cmd/extract-ledger-payloads/README.md
  cmd/extract-ledger-payloads/index.go
  rosetta/identifier/network.go
  rosetta/object/block.go
  rosetta/object/operation.go
  service/mapper/config.go
  service/mapper/mapper.go
Labels: documentation, improvement

#224 Refuse bootstrapping when index exists
  cmd/flow-dps-indexer/README.md
  cmd/flow-dps-indexer/main.go
Labels: documentation, improvement

#200 Add transaction limit to Retriever.Block
  cmd/flow-rosetta-server/README.md
  cmd/flow-rosetta-server/main.go
  rosetta/retriever/config.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_test.go
Labels: improvement, testing

#218 Rosetta network endpoints integration tests
  api/rosetta/data_balance_integration_test.go
  api/rosetta/data_block_integration_test.go
  api/rosetta/data_integration_test.go
  api/rosetta/data_network_integration_test.go
  api/rosetta/data_transaction_integration_test.go
Labels: testing

#223 Add codec component
  api/dps/server.go
  api/dps/server_test.go
  api/rosetta/data_integration_test.go
  cmd/create-index-snapshot/main.go
  cmd/extract-block-events/README.md
  cmd/extract-block-events/main.go
  cmd/extract-block-headers/README.md
  cmd/extract-block-headers/main.go
  cmd/extract-ledger-payloads/README.md
  cmd/extract-ledger-payloads/index.go
  cmd/extract-ledger-payloads/main.go
  cmd/flow-dps-indexer/main.go
  cmd/flow-dps-server/main.go
  codec/zbor/codec.go
  codec/zbor/dictionary.go
  models/index/codec.go
  service/dictionaries/events.go
  service/dictionaries/header.go
  service/dictionaries/payload.go
  service/index/reader.go
  service/index/storage.go
  service/index/writer.go
  service/mapper/mapper.go
  service/storage/auxiliary.go
  service/storage/auxiliary_test.go
  service/storage/encoding.go
  service/storage/library.go
  service/storage/operations.go
  service/storage/operations_test.go
  testing/mocks/codec.go
  testing/snapshots/rosetta.go
Labels: improvement

#227 Add indexing flags to index only specified data
  cmd/flow-dps-indexer/README.md
  cmd/flow-dps-indexer/main.go
  rosetta/retriever/retriever_test.go
  service/mapper/config.go
  service/mapper/mapper.go
Labels: improvement

#228 Multiple consistency improvements
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/index_test.go
  api/dps/server.go
  api/dps/server_test.go
  api/rosetta/balance.go
  api/rosetta/block.go
  api/rosetta/configuration.go
  api/rosetta/data.go
  api/rosetta/data_balance_integration_test.go
  api/rosetta/data_block_integration_test.go
  api/rosetta/data_integration_test.go
  api/rosetta/data_network_integration_test.go
  api/rosetta/data_transaction_integration_test.go
  api/rosetta/length.go
  api/rosetta/networks.go
  api/rosetta/options.go
  api/rosetta/status.go
  api/rosetta/transaction.go
  cmd/create-index-snapshot/main.go
  cmd/flow-dps-indexer/main.go
  docs/dps-api.md
  gen/version.go
  models/convert/cadence_test.go
  models/convert/paths_test.go
  rosetta/configuration/configuration.go
  rosetta/converter/converter.go
  rosetta/converter/converter_test.go
  rosetta/identifier/account.go
  rosetta/identifier/currency.go
  rosetta/identifier/operation.go
  rosetta/invoker/invoker.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_test.go
  service/chain/disk.go
  service/chain/disk_test.go
  service/index/writer.go
  service/mapper/config.go
  service/storage/auxiliary.go
  service/storage/encoding_test.go
Labels: documentation, improvement
