Repository optakt/flow-dps, pull requests merged in 2021-09, with the labels that each got.

#399 Testing improvements
  api/access/server_internal_test.go
  api/dps/index_internal_test.go
  api/dps/server_integration_test.go
  api/dps/server_internal_test.go
  api/rosetta/balance_integration_test.go
  api/rosetta/block_integration_test.go
  api/rosetta/data_integration_test.go
  api/rosetta/networks_integration_test.go
  api/rosetta/options_integration_test.go
  api/rosetta/status_integration_test.go
  api/rosetta/transaction_integration_test.go
  models/convert/cadence_test.go
  models/convert/hash_test.go
  models/convert/paths_test.go
  models/convert/types_test.go
  models/convert/values_test.go
  rosetta/converter/converter_internal_test.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_internal_test.go
  rosetta/retriever/retriever_test.go
  service/chain/disk_test.go
  service/feeder/feeder_internal_test.go
  service/index/index_integration_test.go
  service/invoker/invoker_internal_test.go
  service/invoker/read_internal_test.go
  service/mapper/config_internal_test.go
  service/mapper/fsm_internal_test.go
  service/mapper/pathings_internal_test.go
  service/mapper/state_internal_test.go
  service/mapper/transitions_internal_test.go
  service/storage/auxiliary_internal_test.go
  service/storage/auxiliary_test.go
  service/storage/encoding_internal_test.go
  service/storage/operations_integration_test.go
  service/storage/operations_internal_test.go
  testing/mocks/generic.go
  testing/mocks/reader.go
  testing/mocks/validator.go
Labels: improvement, should, testing

#409 Remove darwin builds from release config
  .goreleaser.yml
Labels: bug, must

#410 Make GitHub actions manually triggerable
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: improvement, could, tools

#416 Add home include directory for protoc generation
  api/dps/api.generate.go
Labels: bug, documentation

#420 Fix protocol buffers compilation and upgrade compiler version
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  api/dps/api.generate.go
  api/dps/api.pb.go
  go.mod
  go.sum
Labels: bug, tools

#400 Add tests for Rosetta Construction API
  api/rosetta/parse.go
  api/rosetta/transactor.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_test.go
  rosetta/transactor/parser.go
  rosetta/transactor/parser_internal_test.go
  rosetta/transactor/parser_test.go
  rosetta/transactor/transactor.go
  rosetta/transactor/transactor_internal_test.go
  rosetta/transactor/transactor_test.go
  testing/mocks/generator.go
  testing/mocks/generic.go
  testing/mocks/submitter.go
Labels: improvement, testing

#446 Live Indexer components unit tests
  cmd/flow-dps-live/main.go
  service/cloud/gcp_streamer_internal_test.go
  service/feeder/feeder_internal_test.go
  service/mapper/pathings_internal_test.go
  service/mapper/transitions_internal_test.go
  service/tracker/consensus_internal_test.go
  service/tracker/consensus_test.go
  service/tracker/execution.go
  service/tracker/execution_internal_test.go
  service/tracker/execution_test.go
  service/tracker/initialize.go
  service/tracker/initialize_test.go
  testing/mocks/feeder.go
  testing/mocks/generic.go
  testing/mocks/record_holder.go
  testing/mocks/record_streamer.go
Labels: testing

#455 Use option in `zbor` and GCP streamer for CBOR decoding
  codec/zbor/codec.go
  docs/dps-api.md
  service/cloud/gcp_streamer.go
  service/cloud/gcp_streamer_internal_test.go
Labels: improvement, should

#457 Add support for indexer restarts
  cmd/flow-access-server/README.md
  cmd/flow-access-server/main.go
  cmd/flow-dps-indexer/README.md
  cmd/flow-dps-indexer/main.go
  cmd/flow-dps-live/README.md
  cmd/flow-dps-live/main.go
  cmd/flow-dps-server/README.md
  cmd/flow-dps-server/main.go
  models/dps/storage.go
  service/chain/disk.go
  service/chain/disk_test.go
  service/cloud/config.go
  service/cloud/gcp_streamer.go
  service/initializer/catchup_blocks.go
  service/initializer/protocol_state.go
  service/initializer/protocol_state_test.go
  service/loader/checkpoint.go
  service/loader/config.go
  service/loader/index.go
  service/mapper/config.go
  service/mapper/config_internal_test.go
  service/mapper/fsm_internal_test.go
  service/mapper/loader.go
  service/mapper/state.go
  service/mapper/state_internal_test.go
  service/mapper/status.go
  service/mapper/transitions.go
  service/mapper/transitions_internal_test.go
  service/storage/auxiliary_test.go
  service/storage/operations.go
  service/tracker/consensus.go
  service/tracker/consensus_internal_test.go
  testing/mocks/loader.go
Labels: feature, must

#458 Add sanity check for mismatch in execution state
  cmd/flow-dps-indexer/main.go
  cmd/flow-dps-live/main.go
  service/mapper/status.go
  service/mapper/transitions.go
  service/mapper/transitions_internal_test.go
  service/tracker/execution_internal_test.go
Labels: feature, should

#467 Remove access API
  .gitignore
  api/access/invoker.go
  api/access/server.go
  api/access/server_internal_test.go
  cmd/flow-access-server/README.md
  cmd/flow-access-server/main.go
  docs/access-api.md
  docs/introduction.md
  go.mod
Labels: improvement, must

#468 Remove sanity check for mismatch in execution state
  cmd/flow-dps-indexer/main.go
  cmd/flow-dps-live/main.go
  service/mapper/status.go
  service/mapper/transitions.go
  service/mapper/transitions_internal_test.go
Labels: bug, must

#465 Reorganize and rewrite documentation
  BENCHMARK.md
  README.md
  cmd/flow-dps-server/README.md
  docs/architecture.md
  docs/database.md
  docs/introduction.md
  docs/snapshots.md
  docs/src/api.nomnoml
  docs/src/flow_dps_indexer.nomnoml
  docs/src/flow_dps_live.nomnoml
  docs/svg/api.svg
  docs/svg/flow_dps_indexer.svg
  docs/svg/flow_dps_live.svg
Labels: documentation, improvement

#479 Add tests for the restart logic
  service/cloud/gcp_streamer_internal_test.go
  service/initializer/catchup_blocks.go
  service/initializer/catchup_blocks_test.go
  service/mapper/transitions.go
  service/mapper/transitions_internal_test.go
  service/storage/operations_internal_test.go
Labels: testing
