Repository optakt/flow-dps, pull requests merged in 2021-08, with the labels that each got.

#323 Construction API base code and Preprocess endpoint
  api/rosetta/client.go
  api/rosetta/construction.go
  api/rosetta/errors.go
  api/rosetta/parser.go
  api/rosetta/preprocess.go
  cmd/flow-rosetta-server/main.go
  go.mod
  go.sum
  models/convert/cadence.go
  rosetta/configuration/errors.go
  rosetta/failure/invalid_intent.go
  rosetta/object/options.go
  rosetta/transactions/create_transaction.go
  rosetta/transactions/generator.go
  rosetta/transactions/intent.go
  rosetta/transactions/parse_transaction.go
  rosetta/transactions/parser.go
  rosetta/transactions/validator.go
Labels: feature

#324 Construction API code - Metadata endpoint
  api/rosetta/errors.go
  api/rosetta/metadata.go
  cmd/flow-rosetta-server/main.go
  rosetta/object/metadata.go
Labels: feature

#329 Rosetta Construction API - Submit endpoint
  api/rosetta/errors.go
  api/rosetta/submit.go
  api/rosetta/transaction.go
  cmd/flow-rosetta-server/main.go
Labels: feature

#334 Add integration tests for DPS API
  api/dps/server_integration_test.go
Labels: improvement, testing

#345 Add validation for GRPC types
  .github/workflows/ci.yml
  api/dps/api.generate.go
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/server.go
  api/dps/server_test.go
  go.mod
  go.sum
Labels: improvement

#359 Rosetta: return zero balance for missing vaults
  api/rosetta/balance_integration_test.go
  rosetta/retriever/retriever.go
Labels: improvement

#365 Fix AutoRelease CI script to install mising dependency
  .github/workflows/release.yml
Labels: bug, must

#366 Fix releaser v2
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: bug

#354 Verify lengths of byte slices in Chain
  service/feeder/disk.go
Labels: improvement

#367 Rosetta: Adding Hash endpoint
  api/rosetta/hash.go
  cmd/flow-rosetta-server/main.go
Labels: feature

#325 Construction API - Payloads endpoint
  api/rosetta/errors.go
  api/rosetta/parser.go
  api/rosetta/payloads.go
  cmd/flow-rosetta-server/main.go
  rosetta/object/signing_payload.go
  rosetta/transactions/compile_transaction.go
  rosetta/transactions/intent.go
  rosetta/transactions/validator.go
Labels: feature
