Repository optakt/flow-dps, pull requests merged in 2021-07, with the labels that each got.

#234 Verify that blockID contains requested transactionID in rosetta transaction endpoint
  .github/workflows/ci.yml
  api/rosetta/data_transaction_integration_test.go
  api/rosetta/errors.go
  api/rosetta/transaction.go
  rosetta/configuration/errors.go
  rosetta/failure/unknown_transaction.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_test.go
  testing/snapshots/rosetta.go
Labels: bug, feature

#238 Mapper unit tests
  api/dps/index.go
  api/dps/index_test.go
  cmd/flow-dps-indexer/main.go
  service/index/reader.go
  service/index/writer.go
  service/mapper/config_test.go
  service/mapper/fsm_test.go
  service/mapper/pathings_test.go
  service/mapper/state_test.go
  service/mapper/transitions_test.go
  testing/mocks/chain.go
  testing/mocks/feeder.go
  testing/mocks/forest.go
  testing/mocks/loader.go
  testing/mocks/writer.go
Labels: testing

#256 Add Flow Access API (only Header endpoints for now)
  README.md
  api/access/server.go
  api/access/server_test.go
  cmd/flow-access-server/README.md
  cmd/flow-access-server/main.go
  docs/access-api.md
  docs/introduction.md
  go.mod
  go.sum
  rosetta/retriever/config.go
  testing/mocks/codec.go
  testing/mocks/generic.go
  testing/mocks/reader.go
Labels: feature

#260 Add Flow Access API (only Header endpoints for now) (#256)
  .github/workflows/ci.yml
  api/access/server_test.go
  api/dps/index_test.go
  api/dps/server_test.go
  cmd/flow-dps-indexer/main.go
  docs/architecture.md
  models/index/writer.go
  rosetta/converter/converter_test.go
  rosetta/retriever/retriever_test.go
  service/chain/disk.go
  service/chain/disk_test.go
  service/index/reader.go
  service/index/storage.go
  service/index/writer.go
  service/mapper/chain.go
  service/mapper/config.go
  service/mapper/fsm_test.go
  service/mapper/pathings_test.go
  service/mapper/state_test.go
  service/mapper/transitions.go
  service/mapper/transitions_test.go
  service/storage/auxiliary_test.go
  service/storage/operations.go
  service/storage/operations_test.go
  service/storage/prefixes.go
  testing/mocks/chain.go
  testing/mocks/codec.go
  testing/mocks/converter.go
  testing/mocks/error.go
  testing/mocks/feeder.go
  testing/mocks/forest.go
  testing/mocks/generator.go
  testing/mocks/generic.go
  testing/mocks/invoker.go
  testing/mocks/loader.go
  testing/mocks/reader.go
  testing/mocks/validator.go
  testing/mocks/writer.go
Labels: documentation, feature, testing

#275 Add go mod cache to CI builds
  .github/workflows/ci.yml
Labels: improvement

#276 Integrate test improvements from Access API feat. branch (#256)
  README.md
  api/dps/index_test.go
  api/dps/server_test.go
  docs/introduction.md
  rosetta/converter/converter_test.go
  rosetta/retriever/config.go
  rosetta/retriever/retriever_test.go
  service/chain/disk_test.go
  service/index/reader.go
  service/mapper/fsm_test.go
  service/mapper/pathings_test.go
  service/mapper/state_test.go
  service/mapper/transitions_test.go
  service/storage/auxiliary_test.go
  service/storage/operations_test.go
  testing/mocks/chain.go
  testing/mocks/codec.go
  testing/mocks/converter.go
  testing/mocks/error.go
  testing/mocks/feeder.go
  testing/mocks/forest.go
  testing/mocks/generator.go
  testing/mocks/generic.go
  testing/mocks/invoker.go
  testing/mocks/loader.go
  testing/mocks/reader.go
  testing/mocks/validator.go
  testing/mocks/writer.go
Labels: improvement

#280 Index seals by height
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/index_test.go
  api/dps/server.go
  api/dps/server_test.go
  cmd/flow-dps-indexer/README.md
  cmd/flow-dps-indexer/main.go
  docs/architecture.md
  models/index/reader.go
  models/index/writer.go
  service/chain/disk.go
  service/chain/disk_test.go
  service/index/reader.go
  service/index/storage.go
  service/index/writer.go
  service/mapper/chain.go
  service/mapper/config.go
  service/mapper/transitions.go
  service/mapper/transitions_test.go
  service/storage/operations.go
  service/storage/operations_test.go
  service/storage/prefixes.go
  testing/mocks/chain.go
  testing/mocks/generic.go
  testing/mocks/reader.go
  testing/mocks/writer.go
Labels: feature

#279 Add meta endpoints
  api/access/server.go
  api/access/server_test.go
  cmd/flow-access-server/main.go
Labels: feature

#277 Add Event Endpoints (#179)
  api/access/server.go
  api/access/server_test.go
  go.mod
Labels: feature

#278 Add collection endpoint to access API
  api/access/server.go
  api/access/server_test.go
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/index_test.go
  api/dps/server.go
  api/dps/server_test.go
  models/index/reader.go
  service/index/reader.go
  testing/mocks/reader.go
Labels: feature

#286 Deduce ChainID from index
  api/access/server.go
  api/access/server_test.go
Labels: dapper, improvement

#283 Add transaction endpoints
  api/access/server.go
  api/access/server_test.go
  api/dps/api.pb.go
  api/dps/api.proto
  api/dps/api_grpc.pb.go
  api/dps/index.go
  api/dps/index_test.go
  api/dps/server.go
  api/dps/server_test.go
  docs/architecture.md
  models/index/reader.go
  service/index/reader.go
  service/index/storage.go
  service/index/writer.go
  service/storage/operations.go
  service/storage/operations_test.go
  service/storage/prefixes.go
  testing/mocks/generic.go
  testing/mocks/reader.go
Labels: feature

#287 Add GoReleaser config and GitHub Action
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
Labels: improvement

#299 Fix releaser script
  .github/workflows/release.yml
Labels: bug

#300 Fix releaser script 2
  .github/workflows/release.yml
Labels: bug

#303 Fix byte slice declarations
  models/convert/paths_test.go
  models/convert/values_test.go
  service/storage/encoding_test.go
  testing/mocks/generic.go
Labels: could, improvement

#305 Index integration tests
  service/index/index_integration_test.go
  service/storage/auxiliary.go
  service/storage/operations_integration_test.go
Labels: improvement, should, testing

#306 Enforce 32-bit encoding for hashes
  service/storage/encoding.go
Labels: improvement, should

#307 Update architecture documentation following the mapper refactor
  docs/architecture.md
Labels: documentation, improvement

#302 Rosetta Identifier -> Qualifier
  api/rosetta/balance.go
  api/rosetta/block.go
  api/rosetta/configuration.go
  api/rosetta/data_integration_test.go
  api/rosetta/networks_integration_test.go
  api/rosetta/retriever.go
  rosetta/retriever/retriever.go
  rosetta/retriever/retriever_test.go
  rosetta/retriever/validator.go
  rosetta/validator/block.go
  testing/mocks/validator.go
Labels: could, improvement
